package com.tw;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
enum State {
    MAINMENU,
    ADDSTUDENT,
    SCOREGENERATER,
}
public class Library {
    public static void main(String [ ] args)
    {
        State state=State.MAINMENU;

        Menu menu=new Menu();
        menu.printMainMenu();

    }
}
